# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OlakaiBeta < Formula
  desc "Olakai CLI for AI observability and coding agent monitoring"
  homepage "https://olakai.ai"
  version "1.0.0-beta.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.3/olakai_1.0.0-beta.3_darwin_amd64.tar.gz"
      sha256 "a947a5e17bea32e1faf8cbcf3376bf61872c8ff29955d6c94fa08dcb7e569d52"

      define_method(:install) do
        bin.install "olakai"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.3/olakai_1.0.0-beta.3_darwin_arm64.tar.gz"
      sha256 "8a9b3ee07be5795f3058f04abeb91de57026a4f5d5cb28cc1c5f6875841b2547"

      define_method(:install) do
        bin.install "olakai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.3/olakai_1.0.0-beta.3_linux_amd64.tar.gz"
      sha256 "f5e121c4ad2d25c0e91f2cccfa33e0cdc845171e7ca609fbdeb97f80b4f01347"
      define_method(:install) do
        bin.install "olakai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.3/olakai_1.0.0-beta.3_linux_arm64.tar.gz"
      sha256 "f9d223dfd1c5256b3c94f2d18186d49775379a15565e3351834ffa65d81cc9b5"
      define_method(:install) do
        bin.install "olakai"
      end
    end
  end

  conflicts_with "olakai-ai/tap/olakai"

  test do
    assert_match version.to_s, shell_output("#{bin}/olakai --version")
  end
end
