# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OlakaiBeta < Formula
  desc "Olakai CLI for AI observability and coding agent monitoring"
  homepage "https://olakai.ai"
  version "1.0.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.1/olakai_1.0.0-beta.1_darwin_amd64.tar.gz"
      sha256 "0a15d44815de257ed94f2b18b43bc96eb437077650af4a63e4012beb38a70251"

      define_method(:install) do
        bin.install "olakai"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.1/olakai_1.0.0-beta.1_darwin_arm64.tar.gz"
      sha256 "ceca8adc2c12cb2440daf89c635244f0c6de0f7c68251c97e89ae25d633a5366"

      define_method(:install) do
        bin.install "olakai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.1/olakai_1.0.0-beta.1_linux_amd64.tar.gz"
      sha256 "faa71ae5df115da32b9cc551e04ec142c2d6eed0f4f737ea57bcb27dd0e7c8e2"
      define_method(:install) do
        bin.install "olakai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.1/olakai_1.0.0-beta.1_linux_arm64.tar.gz"
      sha256 "5d22439aeb0df80cb1a1c2aab9d60957ae3a78d01f74209085a7b6b5740eb23f"
      define_method(:install) do
        bin.install "olakai"
      end
    end
  end

  conflicts_with "olakai-ai/tap/olakai"

  test do
    assert_match version.to_s, shell_output("#{bin}/olakai --version")
  end
end
