# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OlakaiBeta < Formula
  desc "Olakai CLI for AI observability and coding agent monitoring"
  homepage "https://olakai.ai"
  version "1.0.0-beta.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.2/olakai_1.0.0-beta.2_darwin_amd64.tar.gz"
      sha256 "e547ed10a5cc7615710eb90f2d083d29b8b24294b1b6ebdc3eabfa4a76d47ec6"

      define_method(:install) do
        bin.install "olakai"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.2/olakai_1.0.0-beta.2_darwin_arm64.tar.gz"
      sha256 "47a0c89dd7dda43947e1d8634112e82a68348231da326d2f5fa4e2673ab1dee3"

      define_method(:install) do
        bin.install "olakai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.2/olakai_1.0.0-beta.2_linux_amd64.tar.gz"
      sha256 "ae6fd3bc2f6212256f2ab58354f1074f374df3c62001f2113a5f261f734acf3f"
      define_method(:install) do
        bin.install "olakai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.olakai.ai/cli/releases/go-v1.0.0-beta.2/olakai_1.0.0-beta.2_linux_arm64.tar.gz"
      sha256 "9cb7a31def88b8a036e6ba6d25efd5a302a2b7d2f9740b0463c78be6b129e168"
      define_method(:install) do
        bin.install "olakai"
      end
    end
  end

  conflicts_with "olakai-ai/tap/olakai"

  test do
    assert_match version.to_s, shell_output("#{bin}/olakai --version")
  end
end
